services:
  - type: web
    name: movieplex
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn movieplex.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: movieplex.settings
      - key: PYTHON_VERSION
        value: 3.10

